//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.13 at 10:35:51 AM YEKT
//


package com.kreig133.daogenerator.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for configurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configurationType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="type" use="required" type="{com.aplana.dao-generator}selectType" />
 *       &lt;attribute name="multipleResult" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configurationType", propOrder = {
    "value"
})
public class ConfigurationType {

    @XmlValue
    protected String value;
    @XmlAttribute(required = true)
    protected SelectType type;
    @XmlAttribute
    protected Boolean multipleResult;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SelectType }
     *     
     */
    public SelectType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectType }
     *     
     */
    public void setType(SelectType value) {
        this.type = value;
    }

    /**
     * Gets the value of the multipleResult property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public boolean isMultipleResult() {
        if (multipleResult == null) {
            return true;
        } else {
        return multipleResult;
    }
    }

    /**
     * Sets the value of the multipleResult property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultipleResult(Boolean value) {
        this.multipleResult = value;
    }

}
