//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.13 at 10:35:51 AM YEKT
//


package com.kreig133.daogenerator.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="common" type="{com.aplana.dao-generator}commonType"/>
 *         &lt;element name="inputParametrs" type="{com.aplana.dao-generator}parametersType" minOccurs="0"/>
 *         &lt;element name="outputParametrs" type="{com.aplana.dao-generator}parametersType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "common",
    "inputParametrs",
    "outputParametrs"
})
@XmlRootElement(name = "daoMethod")
public class DaoMethod {

    @XmlElement(required = true)
    protected CommonType common;
    protected ParametersType inputParametrs;
    protected ParametersType outputParametrs;

    /**
     * Gets the value of the common property.
     * 
     * @return
     *     possible object is
     *     {@link CommonType }
     *     
     */
    public CommonType getCommon() {
        return common;
    }

    /**
     * Sets the value of the common property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonType }
     *     
     */
    public void setCommon(CommonType value) {
        this.common = value;
    }

    /**
     * Gets the value of the inputParametrs property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersType }
     *     
     */
    public ParametersType getInputParametrs() {
        return inputParametrs;
    }

    /**
     * Sets the value of the inputParametrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersType }
     *     
     */
    public void setInputParametrs(ParametersType value) {
        this.inputParametrs = value;
    }

    /**
     * Gets the value of the outputParametrs property.
     * 
     * @return
     *     possible object is
     *     {@link ParametersType }
     *     
     */
    public ParametersType getOutputParametrs() {
        return outputParametrs;
    }

    /**
     * Sets the value of the outputParametrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParametersType }
     *     
     */
    public void setOutputParametrs(ParametersType value) {
        this.outputParametrs = value;
    }

}
