//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.13 at 10:35:51 AM YEKT
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.aplana.dao-generator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kreig133.daogenerator.jaxb;
