//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.05 at 01:30:12 PM YEKST 
//


package com.kreig133.daogenerator.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for parentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="parentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DEFAULT"/>
 *     &lt;enumeration value="CATALOGUE"/>
 *     &lt;enumeration value="SAVED_QUERY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "parentType")
@XmlEnum
public enum ParentType {

    DEFAULT("По умолчанию"),
    CATALOGUE("Справочник"),
    //не представлен в схеме
    WITH_PAGING("Вы не должны это видеть!"),
    SAVED_QUERY("Сохраненный запрос");

    final String decription;

    private ParentType( String decription ) {
        this.decription = decription;
    }

    public String getDecription() {
        return decription;
    }

    public String value() {
        return name();
    }

    public static ParentType fromValue(String v) {
        return valueOf(v);
    }

    @Override
    public String toString() {
        return decription;
    }
}
