//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.10 at 06:03:21 PM GMT+05:00 
//


package com.kreig133.daogenerator.jaxb;

import com.kreig133.daogenerator.db.extractor.OutputParameterExtractor;
import com.kreig133.daogenerator.db.extractor.QueryOutputParameterExtractor;
import com.kreig133.daogenerator.db.extractor.SpOutputParameterExtractor;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="selectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CALL"/>
 *     &lt;enumeration value="SELECT"/>
 *     &lt;enumeration value="GENERATE"/>
 *     &lt;enumeration value="GENEROUT"/>
 *     &lt;enumeration value="INSERT"/>
 *     &lt;enumeration value="DELETE"/>
 *     &lt;enumeration value="UPDATE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "selectType")
@XmlEnum
public enum SelectType {

    CALL    ("Select", new SpOutputParameterExtractor   () ),
    SELECT  ("Select", new QueryOutputParameterExtractor() ),
    INSERT  ("Insert", null ),
    DELETE  ("Delete", null ),
    UPDATE  ("Update", null );

    private final String annotation;

    private final OutputParameterExtractor outputParameterExtractor;

    public String getAnnotation() {
        return annotation;
    }

    public OutputParameterExtractor getOutputParameterExtractor() {
        return outputParameterExtractor;
    }

    SelectType( String annotation, OutputParameterExtractor extractor ) {
        this.annotation = annotation;
        this.outputParameterExtractor = extractor;
    }

    public static SelectType getByName( String name ){
        name = name.trim().toLowerCase();
        for( SelectType selectType: SelectType.values() ){
            if( selectType.toString().toLowerCase().equals( name ) ){
                return selectType;
            }
        }

        return null;
    }

    public boolean isQuery(  ){
        return
                this == SELECT ||
                this == INSERT ||
                this == DELETE ||
                this == UPDATE;
    }

}
