package com.kreig133.daogenerator.common;

import com.kreig133.daogenerator.parameter.Parameter;

import java.util.List;

/**
 * @author eshangareev
 * @version 1.0
 */
public class InOutClass {
    public static final String PACKAGE = "com.aplana.sbrf.deposit.persistence.custom.entity.accounts.operation.administrative.closecount";
    private static final String COMMENT_TO_CLASS = "/**\n" +
                                           " * Generated by DaoGenerator 0.2\n"+
                                           " * @author eshangareev\n" +
                                           " * @version 1.0\n" +
                                           " */\n";
    private static final String IMPORTS = "import java.io.Serializable;\n" +
                                  "import java.util.*;\n\n";


    private final List< Parameter > parameters;
    private String name;

    public InOutClass( List< Parameter > parameters, String name) {
        this.parameters = parameters;
        this.name = name;
    }
    @Override
    public String toString() {
        StringBuilder result = new StringBuilder();
        result.append("package ");
        result.append(PACKAGE);
        result.append(";\n\n");
        result.append(IMPORTS);
        result.append(COMMENT_TO_CLASS);
        result.append("public class "); result.append(name); result.append(" implements Serializable {\n\n");

        for(Parameter p : parameters){
            result.append(p.toString());
            result.append(p.generateGetter());
            result.append(p.generateSetter());
        }
        result.append("}");

        return result.toString();
    }

    public String getName() {
        return name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    public List<Parameter> getParameters() {
        return parameters;
    }
}
