//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.12 at 10:59:31 PM GMT+05:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.aplana.iask.task", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kreig133.daogenerator.task.model;
